displayName: "High 5xx Error Rate - Load Balancer"
documentation:
  content: "The load balancer is experiencing a high rate of 5xx errors (>5% of requests). This indicates backend service issues that need immediate attention."
  mimeType: "text/markdown"
conditions:
  - displayName: "5xx error rate > 5%"
    conditionThreshold:
      filter: 'resource.type="https_lb_rule" AND metric.type="loadbalancing.googleapis.com/https/request_count" AND metric.labels.response_code_class="500"'
      aggregations:
        - alignmentPeriod: "60s"
          perSeriesAligner: "ALIGN_RATE"
          crossSeriesReducer: "REDUCE_SUM"
          groupByFields:
            - "resource.url_map_name"
      comparison: "COMPARISON_GT"
      thresholdValue: 0.05
      duration: "300s"
combiner: "OR"
enabled: true