displayName: "High Latency - Load Balancer"
documentation:
  content: "The load balancer is experiencing high latency (95th percentile > 2000ms). This may indicate backend performance issues or network problems."
  mimeType: "text/markdown"
conditions:
  - displayName: "95th percentile latency > 2000ms"
    conditionThreshold:
      filter: 'resource.type="https_lb_rule" AND metric.type="loadbalancing.googleapis.com/https/total_latencies"'
      aggregations:
        - alignmentPeriod: "60s"
          perSeriesAligner: "ALIGN_DELTA"
          crossSeriesReducer: "REDUCE_PERCENTILE_95"
          groupByFields:
            - "resource.url_map_name"
      comparison: "COMPARISON_GT"
      thresholdValue: 2000
      duration: "300s"
combiner: "OR"
enabled: true